name: Convert time-based version string to NuGet format
author: Sander Saares
description: Takes a time-based version string and ensures it is in NuGet compatible format.
inputs:
  versionstring:
    description: The original version string from make-time-based-version-string.
    required: true
outputs:
  NUGET_VERSION_STRING:
    description: The version string in NuGet format
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'crosshair'
  color: 'red'